name: Auto Sync To External Branch
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: self-hosted

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 2

      - name: Set up Git credential
        run: |
          git config --global user.name 'gooishin'
          git config --global user.email 'shing.shan.gooi@intel.com'

      - name: Checkout destination repo
        run: |
          cd /home/user/actions-runner/_work/
          git clone https://${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}@github.com/gooishin/Test_Destination_repo.git

      - name: Exclude .github sync to external
        run: |
         cd /home/user/actions-runner/_work/Test_source_repo/Test_source_repo
         echo ".github/" >> .gitignore
         git add .gitignore
         git commit -m "ignore .github" .gitignore
         
      - name: Create branch at destination repo
        run: |
          cd /home/user/actions-runner/_work/Test_Destination_repo
          git checkout -b update-branch
      
      - name: Push to destination repository
        run: |
          cd /home/user/actions-runner/_work/Test_source_repo/Test_source_repo
          git remote add destination "https://github.com/gooishin/Test_Destination_repo.git"
          git push destination main:update-branch --force

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: 'gooishin',
              repo: 'Test_Destination_repo',
              state: 'open',
              head: 'gooishin:update-main',
              base: 'main'
            });
          
            if (pullRequests.length === 0) {
              await github.pulls.create({
                owner: 'gooishin',
                repo: 'Test_Destination_repo',
                title: 'Sync main branch from source repo',
                head: 'update-main',
                base: 'main',
                body: 'This PR syncs the main branch from the source repository to the destination repository.'
              });
            } else {
              console.log('A pull request already exists:', pullRequests[0].html_url);
            }
